execute_process(COMMAND git rev-parse HEAD WORKING_DIRECTORY "${PROFILE_SOURCE_DIR}" OUTPUT_VARIABLE profile_commit OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND git diff --binary HEAD -- WORKING_DIRECTORY "${PROFILE_SOURCE_DIR}" OUTPUT_VARIABLE profile_diff COMMAND_ERROR_IS_FATAL ANY)
string(SHA256 profile_diff_hash "${profile_diff}")
execute_process(COMMAND git status --porcelain=v1 --untracked-files=no WORKING_DIRECTORY "${PROFILE_SOURCE_DIR}" OUTPUT_VARIABLE profile_status OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
file(GLOB_RECURSE profile_inputs LIST_DIRECTORIES false "${PROFILE_SOURCE_DIR}/modules/runtime/tests/*")
list(SORT profile_inputs)
set(profile_test_hashes "")
foreach(profile_input IN LISTS profile_inputs)
    file(SHA256 "${profile_input}" profile_hash)
    file(RELATIVE_PATH profile_relative "${PROFILE_SOURCE_DIR}" "${profile_input}")
    string(APPEND profile_test_hashes "${profile_relative} ${profile_hash}\n")
endforeach()
string(SHA256 profile_tests_hash "${profile_test_hashes}")
file(GLOB_RECURSE profile_runtime_inputs LIST_DIRECTORIES false "${PROFILE_SOURCE_DIR}/modules/runtime/include/*.h" "${PROFILE_SOURCE_DIR}/modules/runtime/src/*.h" "${PROFILE_SOURCE_DIR}/modules/runtime/src/*.cpp")
list(APPEND profile_runtime_inputs "${PROFILE_SOURCE_DIR}/modules/runtime/CMakeLists.txt")
list(SORT profile_runtime_inputs)
set(profile_runtime_hashes "")
foreach(profile_input IN LISTS profile_runtime_inputs)
    file(SHA256 "${profile_input}" profile_hash)
    file(RELATIVE_PATH profile_relative "${PROFILE_SOURCE_DIR}" "${profile_input}")
    string(APPEND profile_runtime_hashes "${profile_relative} ${profile_hash}\n")
endforeach()
string(SHA256 profile_runtime_hash "${profile_runtime_hashes}")
set(profile_harness_hashes "")
foreach(profile_name IN ITEMS test_runtime_profile.cpp runtime_profile_support.h runtime_profile_integrated.h runtime_profile_submission.h profile_build_identity.cmake run_runtime_profile.ps1 runtime_profile_runner_support.ps1 runtime_profile_capture_support.ps1 runtime_profile_trace.py runtime_profile_compare.py)
    file(SHA256 "${PROFILE_SOURCE_DIR}/modules/runtime/tests/${profile_name}" profile_hash)
    string(APPEND profile_harness_hashes "${profile_name} ${profile_hash}\n")
endforeach()
string(SHA256 profile_harness_hash "${profile_harness_hashes}")
if(profile_status STREQUAL "")
    set(profile_dirty "false")
else()
    set(profile_dirty "true")
endif()
if(DEFINED PROFILE_AUDIT_OUTPUT)
    file(WRITE "${PROFILE_AUDIT_OUTPUT}" "{\"commit\":\"${profile_commit}\",\"trackedDirty\":${profile_dirty},\"trackedDiffSha256\":\"${profile_diff_hash}\",\"runtimeTestsSha256\":\"${profile_tests_hash}\",\"runtimeSourcesSha256\":\"${profile_runtime_hash}\",\"harnessSha256\":\"${profile_harness_hash}\"}\n")
endif()
if(DEFINED PROFILE_OUTPUT)
    set(profile_header "#pragma once\nnamespace radray::profile {\ninline constexpr char BuildCommit[] = R\"identity(${profile_commit})identity\";\ninline constexpr char BuildDiffHash[] = R\"identity(${profile_diff_hash})identity\";\ninline constexpr char BuildTestsHash[] = R\"identity(${profile_tests_hash})identity\";\ninline constexpr char BuildRuntimeHash[] = R\"identity(${profile_runtime_hash})identity\";\ninline constexpr char BuildHarnessHash[] = R\"identity(${profile_harness_hash})identity\";\ninline constexpr char BuildCompiler[] = R\"identity(${PROFILE_COMPILER})identity\";\ninline constexpr char BuildFlags[] = R\"identity(${PROFILE_FLAGS})identity\";\ninline constexpr char BuildConfiguration[] = R\"identity(${PROFILE_CONFIG})identity\";\ninline constexpr bool BuildTrackedDirty = ${profile_dirty};\n}\n")
    file(WRITE "${PROFILE_OUTPUT}.tmp" "${profile_header}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${PROFILE_OUTPUT}.tmp" "${PROFILE_OUTPUT}" COMMAND_ERROR_IS_FATAL ANY)
    file(REMOVE "${PROFILE_OUTPUT}.tmp")
endif()
