target("libjpeg")
    set_kind("static")
    set_languages("c11")
    add_files("jaricom.c", "jcapimin.c", "jcapistd.c", "jcarith.c", "jccoefct.c", "jccolor.c")
    add_files("jcdctmgr.c", "jchuff.c", "jcinit.c", "jcmainct.c", "jcmarker.c", "jcmaster.c")
    add_files("jcomapi.c", "jcparam.c", "jcprepct.c", "jcsample.c", "jctrans.c", "jdapimin.c")
    add_files("jdapistd.c", "jdarith.c", "jdatadst.c", "jdatasrc.c", "jdcoefct.c", "jdcolor.c")
    add_files("jddctmgr.c", "jdhuff.c", "jdinput.c", "jdmainct.c", "jdmarker.c", "jdmaster.c")
    add_files("jdmerge.c", "jdpostct.c", "jdsample.c", "jdtrans.c", "jerror.c", "jfdctflt.c")
    add_files("jfdctfst.c", "jfdctint.c", "jidctflt.c", "jidctfst.c", "jidctint.c", "jquant1.c")
    add_files("jquant2.c", "jutils.c", "jmemmgr.c", "jmemansi.c")
    if is_plat("windows") then
        add_defines("_CRT_SECURE_NO_DEPRECATE", "_CRT_NONSTDC_NO_DEPRECATE")
    end
    add_vectorexts("sse", "sse2", "ssse3", "sse4.2", "avx", "avx2")
    local incDir = path.absolute(path.join(os.projectdir(), "ext", "libjpeg_include", "include"))
    add_includedirs(incDir, {public = true})
    add_headerfiles("jerror.h", "jmorecfg.h", "jpeglib.h", "jconfig.h")
target_end()
