target("bench_read_obj")
    add_rules("radray_basic_setting", "radray_bench")
    add_files("bench_read_obj.cpp")
    add_deps("radray_core")
    add_tests("bench")
    after_build(function (target) 
        local helper = import("scripts.helper", {rootdir = os.projectdir()})
        helper.copy_app_data(target, false, "assets")
    end)
    after_install(function (target) 
        local helper = import("scripts.helper", {rootdir = os.projectdir()})
        helper.copy_app_data(target, true, "assets")
    end)
