target("test_buddy_alloc")
    set_kind("binary")
    add_rules("radray_basic_setting")
    add_files("test_buddy_alloc.cpp")
    add_deps("radray_core")
    set_default(false)
    add_tests("default")
target_end()

target("test_str_convert")
    set_kind("binary")
    add_rules("radray_basic_setting")
    add_files("test_str_convert.cpp")
    add_deps("radray_core")
    set_default(false)
    add_tests("default")
target_end()

target("test_byte_to_dword")
    set_kind("binary")
    add_rules("radray_basic_setting")
    add_files("test_byte_to_dword.cpp")
    add_deps("radray_core")
    set_default(false)
    add_tests("default")
target_end()

-- target("test_nri")
--     set_kind("binary")
--     add_rules("radray_basic_setting")
--     add_files("test_nri.cpp")
--     add_deps("radray_core", "radray_window", "nri")
-- target_end()

target("test_range_alloc")
    set_kind("binary")
    add_rules("radray_basic_setting")
    add_files("test_range_alloc.cpp")
    add_deps("radray_core")
    set_default(false)
    add_tests("default")
target_end()

includes("hello_world_dx12")
includes("direct_light")
