<#
.SYNOPSIS
    Compile ImGui HLSL shaders to Metal metallib and generate C++ byte array.

.DESCRIPTION
    Pipeline:
      1. Run compile_imgui_metallib tool (HLSL -> SPIR-V -> MSL via ConvertSpirvToMsl)
      2. xcrun metal -std=metal3.0 -O2 (MSL -> AIR)
      3. xcrun metallib (AIR -> metallib)
      4. Convert metallib binary to C++ byte array
      5. Write to modules/imgui/src/dear_imgui_shader_metallib.cpp

.PARAMETER ToolBinary
    Path to the compile_imgui_metallib executable.

.EXAMPLE
    pwsh tools/compile_imgui_metallib/compile.ps1 -ToolBinary build_debug/_build/Debug/compile_imgui_metallib
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$ToolBinary
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = (Resolve-Path "$ScriptDir/../..").Path
$OutputCpp = Join-Path $ProjectRoot "modules/imgui/src/dear_imgui_shader_metallib.cpp"

$MetalStd = "metal3.0"
$MetalOpt = "-O2"

$TmpDir = Join-Path ([System.IO.Path]::GetTempPath()) "imgui_metallib_$(Get-Random)"
New-Item -ItemType Directory -Path $TmpDir -Force | Out-Null

try {
    # Step 1: HLSL -> SPIR-V -> MSL
    Write-Host "[1/4] Generating MSL from HLSL..."
    Write-Host "  > $ToolBinary $TmpDir"
    & $ToolBinary $TmpDir
    if ($LASTEXITCODE -ne 0) { throw "compile_imgui_metallib failed" }

    $VsMetal = Join-Path $TmpDir "imgui_vs.metal"
    $PsMetal = Join-Path $TmpDir "imgui_ps.metal"
    $VsAir = Join-Path $TmpDir "imgui_vs.air"
    $PsAir = Join-Path $TmpDir "imgui_ps.air"
    $MetallibPath = Join-Path $TmpDir "imgui.metallib"

    # Step 2: MSL -> AIR
    Write-Host "[2/4] Compiling MSL to AIR..."
    Write-Host "  > xcrun metal -std=$MetalStd $MetalOpt -c $VsMetal -o $VsAir"
    & xcrun metal "-std=$MetalStd" $MetalOpt -c $VsMetal -o $VsAir
    if ($LASTEXITCODE -ne 0) { throw "metal compile VS failed" }

    Write-Host "  > xcrun metal -std=$MetalStd $MetalOpt -c $PsMetal -o $PsAir"
    & xcrun metal "-std=$MetalStd" $MetalOpt -c $PsMetal -o $PsAir
    if ($LASTEXITCODE -ne 0) { throw "metal compile PS failed" }

    # Step 3: AIR -> metallib
    Write-Host "[3/4] Linking metallib..."
    Write-Host "  > xcrun metallib $VsAir $PsAir -o $MetallibPath"
    & xcrun metallib $VsAir $PsAir -o $MetallibPath
    if ($LASTEXITCODE -ne 0) { throw "metallib link failed" }

    $MetallibSize = (Get-Item $MetallibPath).Length
    Write-Host "  metallib size: $MetallibSize bytes"

    # Step 4: Generate C++ source
    Write-Host "[4/4] Generating C++ byte array..."
    $Bytes = [System.IO.File]::ReadAllBytes($MetallibPath)
    $HexLines = [System.Collections.Generic.List[string]]::new()
    for ($i = 0; $i -lt $Bytes.Length; $i += 16) {
        $End = [Math]::Min($i + 16, $Bytes.Length)
        $Chunk = $Bytes[$i..($End - 1)]
        $HexStr = ($Chunk | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
        $HexLines.Add("    $HexStr,")
    }

    $CppContent = @"
// This file is auto-generated. Do not edit manually.
// Generated by tools/compile_imgui_metallib
#include <span>
#include <radray/types.h>

namespace radray {

// clang-format off
const uint8_t RADRAY_IMGUI_METALLIB[] = {
$($HexLines -join "`n")
};
// clang-format on

std::span<const byte> GetImGuiShaderMETALLIB() noexcept {
    return std::as_bytes(std::span{RADRAY_IMGUI_METALLIB});
}

}  // namespace radray
"@

    [System.IO.File]::WriteAllText($OutputCpp, $CppContent)
    Write-Host "  Written to: $OutputCpp"
    Write-Host "Done."
}
finally {
    Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue
}
