package("dxc_radray")
    set_urls("https://github.com/ksgfk/dxc_bin/releases/download/$(version)/dxc-$(version).zip")

    add_versions("v1.8.2407", "4fd123791a0ffb1eb431303aa2903cf759d73db941c073bc05eab5e95a1411d2")

    on_install("windows|x64", function (package)
        os.cp("win-x64/bin/*", package:installdir("bin"))
        os.cp("include/*", package:installdir("include"))
        package:addenv("PATH", "bin")
    end)

    on_install("windows|arm64", function (package)
        os.cp("win-arm64/bin/*", package:installdir("bin"))
        os.cp("include/*", package:installdir("include"))
        package:addenv("PATH", "bin")
    end)

    on_install("linux|x64", function (package)
        os.cp("linux-x64/bin/*", package:installdir("bin"))
        os.cp("include/*", package:installdir("include"))
        os.cp("linux-x64/lib/*", package:installdir("lib"))
        package:addenv("PATH", "bin")
        package:addenv("PATH", "lib")
    end)

    on_install("macosx|x64", function (package)
        os.cp("macosx-x64/bin/*", package:installdir("bin"))
        os.cp("include/*", package:installdir("include"))
        os.cp("macosx-x64/lib/*", package:installdir("lib"))
        package:addenv("PATH", "bin")
        package:addenv("PATH", "lib")
    end)

    on_install("macosx|arm64", function (package)
        os.cp("macosx-arm64/bin/*", package:installdir("bin"))
        os.cp("include/*", package:installdir("include"))
        os.cp("macosx-arm64/lib/*", package:installdir("lib"))
        package:addenv("PATH", "bin")
        package:addenv("PATH", "lib")
    end)

    on_test(function (package)
        os.vrun("dxc -help")
    end)
