// Generated by tools/generate_forward_cbuffers.py; do not edit.
#pragma once

#include <cstdint>
#include <type_traits>

#include <radray/runtime/render_framework/hlsl_math.h>

namespace radray {

struct DirectionalLight {
    float4 Direction;
    float4 Irradiance;
};
static_assert(sizeof(DirectionalLight) == 32);
static_assert(std::is_standard_layout_v<DirectionalLight> && std::is_trivially_copyable_v<DirectionalLight>);

struct Forward_EffectsData {
    float4x4 InverseProjection;
    float4x4 InverseViewProjection;
    float4x4 PreviousViewProjection;
    float4x4 WorldToView;
    float4x4 Projection;
    float4 Extent;
    float4 Options;
    float4 Eye;
    uint32_t LocalLightCount;
    uint32_t TileCapacity;
    uint32_t HistoryValid;
    uint32_t DebugMode;
};
static_assert(sizeof(Forward_EffectsData) == 384);
static_assert(std::is_standard_layout_v<Forward_EffectsData> && std::is_trivially_copyable_v<Forward_EffectsData>);

struct Forward_MaterialData {
    float4 BaseColor;
    float4 Surface;
    float4 Transmission;
    float4 UVTransform;
};
static_assert(sizeof(Forward_MaterialData) == 64);
static_assert(std::is_standard_layout_v<Forward_MaterialData> && std::is_trivially_copyable_v<Forward_MaterialData>);

struct Forward_ObjectData {
    float4x4 LocalToWorld;
    float4x4 NormalToWorld;
    float4x4 PreviousLocalToWorld;
    uint32_t MotionValid;
};
static_assert(sizeof(Forward_ObjectData) == 196);
static_assert(std::is_standard_layout_v<Forward_ObjectData> && std::is_trivially_copyable_v<Forward_ObjectData>);

struct Forward_OutputSurfaceData {
    float4x4 LocalToClip;
    float4 Options;
};
static_assert(sizeof(Forward_OutputSurfaceData) == 80);
static_assert(std::is_standard_layout_v<Forward_OutputSurfaceData> && std::is_trivially_copyable_v<Forward_OutputSurfaceData>);

struct Forward_PassData {
    float4x4 ShadowMatrix0;
    float4x4 ShadowMatrix1;
    float4x4 ShadowMatrix2;
    float4x4 ShadowMatrix3;
    float4 ShadowSphere[4];
    float4 ShadowBias[4];
    float4 ShadowParams;
    float4 Extent;
    uint32_t LocalLightCount;
    uint32_t UseTiles;
    uint32_t UseAo;
    uint32_t Transparent;
};
static_assert(sizeof(Forward_PassData) == 432);
static_assert(std::is_standard_layout_v<Forward_PassData> && std::is_trivially_copyable_v<Forward_PassData>);

struct PointLight {
    float4 Position;
    float4 Intensity;
};
static_assert(sizeof(PointLight) == 32);
static_assert(std::is_standard_layout_v<PointLight> && std::is_trivially_copyable_v<PointLight>);

struct Forward_ViewData {
    float4x4 ViewProj;
    float4x4 PreviousViewProj;
    float4 EyePosition;
    uint32_t DirectionalLightCount;
    uint32_t PointLightCount;
    float2 LightCountPadding;
    DirectionalLight DirectionalLights[8];
    PointLight PointLights[8];
};
static_assert(sizeof(Forward_ViewData) == 672);
static_assert(std::is_standard_layout_v<Forward_ViewData> && std::is_trivially_copyable_v<Forward_ViewData>);

}  // namespace radray
