add_executable(example_pipeline_probe pipeline_probe.cpp)
target_link_libraries(example_pipeline_probe PRIVATE radrayruntime)
target_compile_definitions(example_pipeline_probe PRIVATE RADRAY_PROJECT_DIR_DEFAULT="${CMAKE_SOURCE_DIR}")
if (RADRAY_ENABLE_SHADER_JIT)
    target_compile_definitions(example_pipeline_probe PRIVATE RADRAY_ENABLE_SHADER_JIT)
    radray_deploy_dxc_runtime(example_pipeline_probe)
endif()
radray_default_compile_flags(example_pipeline_probe)
radray_optimize_flags_binary(example_pipeline_probe)
radray_set_build_path(example_pipeline_probe)
