package("ext_eigen")
    set_sourcedir(path.join(os.scriptdir(), "eigen"))
    add_deps("cmake")
    add_includedirs("include/eigen3")
    on_install(function(package)
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_TESTING=OFF")
        import("package.tools.cmake").install(package, configs)
    end)
package_end()

package("ext_spdlog")
    set_sourcedir(path.join(os.scriptdir(), "spdlog"))
    add_deps("cmake")
    on_install(function(package)
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DSPDLOG_BUILD_SHARED=OFF")
        table.insert(configs, "-DSPDLOG_DISABLE_DEFAULT_LOGGER=ON")
        table.insert(configs, "-DSPDLOG_NO_THREAD_ID=ON")
        import("package.tools.cmake").install(package, configs)
    end)
package_end()
