target("radray_d3d12")
    set_kind("static")
    add_rules("radray_basic_setting")
    add_files("*.cpp")
    add_deps("radray_core", "directx-headers", "d3d12ma")
    add_syslinks("d3d12", "dxgi", "dxguid")
target_end()
