target("test_img_rw")
    add_rules("radray_basic_setting", "radray_test")
    add_files("main.cpp", "../test_main.cpp")
    add_deps("radray_core")
    add_tests("default")
    after_build(function (target) 
        local helper = import("scripts.helper", {rootdir = os.projectdir()})
        helper.copy_app_data(target, false, "assets")
    end)
    after_install(function (target) 
        local helper = import("scripts.helper", {rootdir = os.projectdir()})
        helper.copy_app_data(target, true, "assets")
    end)
target_end()
