target("direct_light")
    set_kind("binary")
    add_rules("radray_basic_setting", "radray_app", "radray_copy_shaders_to_bin")
    add_files("*.cpp")
    add_deps("radray_core", "radray_window", "radray_render")
    after_build(function (target) 
        local helper = import("scripts.helper", {rootdir = os.projectdir()})
        helper.copy_app_data(target, false, "assets")
    end)
    after_install(function (target) 
        local helper = import("scripts.helper", {rootdir = os.projectdir()})
        helper.copy_app_data(target, true, "assets")
    end)
