target("radray_d3d12")
    add_rules("radray_basic_setting")
    set_kind("static")
    add_includedirs(path.join(os.projectdir(), "ext", "DirectXTK12"), {public = true})
    add_files("*.cpp")
    add_deps("radray_core")
    set_pcxxheader("pch.h")
    add_syslinks("dxgi", "d3d12")
target_end()
