"""Regenerate built-in UI artifacts with the current RadRay compiler, or verify them."""
import argparse
import hashlib
from pathlib import Path
import subprocess
import tempfile
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root / "modules/runtime/src/imgui/imgui_shaders.inc"
    lines = ["// Generated by tools/generate_imgui_shaders.py; do not edit."]
    for source in ("ui/imgui.hlsl", "ui/composite.hlsl", "core/platform.hlsli", "core/color.hlsli"):
        lines.append(f"// shaderlib/{source}: SHA256 {hashlib.sha256((root / 'shaderlib' / source).read_bytes()).hexdigest()}")
    with tempfile.TemporaryDirectory(prefix="radray-imgui-") as temporary:
        for name in ("imgui", "composite"):
            prefix = Path(temporary) / name
            subprocess.run([str(args.compiler.resolve()), "--shader-root", str(root / "shaderlib"),
                            "--source", f"ui/{name}.hlsl", "--output", str(prefix), "--target", "all"], check=True)
            for backend in ("dxil", "spirv"):
                data = prefix.with_suffix(f".{backend}.bin").read_bytes()
                if len(data) < 152 or data[:8] != b"RDRY\x07\x00\x98\x00":
                    sys.exit("Unexpected compiler metadata schema; update the generator with the shader contract")
                identity = ",".join(str(value) for value in data[136:152])
                lines.append(f"static constexpr shader::GpuArtifactHash {name}_{backend}_identity{{{{{identity}}}}};")
                lines.append(f"static constexpr unsigned char {name}_{backend}[] = {{")
                for offset in range(0, len(data), 24):
                    lines.append("    " + ",".join(str(value) for value in data[offset:offset + 24]) + ",")
                lines.append("};")
    content = "\n".join(lines) + "\n"
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            sys.exit("Built-in ImGui artifacts differ; regenerate with the pinned compiler")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    main()
