# IJG libjpeg，源码在 third_party/libjpeg（project_manifest.json 的 jpeg-10）。
# 上游发布包没有可 add_subdirectory 的 CMake。库源文件对齐 makefile.vc 的 LIBOBJECTS，
# 内存管理只用 jmemnobs.c。jconfig.h 写到构建目录，不修改 third_party。

function(radray_add_libjpeg)
    set(source_dir "${RADRAY_THIRDPARTY_ROOT}/libjpeg")
    if (NOT EXISTS "${source_dir}/jpeglib.h")
        message(FATAL_ERROR
            "IJG libjpeg sources not found at ${source_dir}. "
            "Run: python tools/fetch_third_party.py restore --only libjpeg")
    endif()

    set(generated_dir "${CMAKE_BINARY_DIR}/libjpeg")
    file(MAKE_DIRECTORY "${generated_dir}")
    file(WRITE "${generated_dir}/jconfig.h" [=[
/* Generated by cmake/libjpeg.cmake. Based on IJG jconfig.vc for the library
 * itself. cjpeg/djpeg switches are omitted; the memory manager is jmemnobs.c.
 */
#define HAVE_PROTOTYPES
#define HAVE_UNSIGNED_CHAR
#define HAVE_UNSIGNED_SHORT
#undef CHAR_IS_UNSIGNED
#define HAVE_STDDEF_H
#define HAVE_STDLIB_H
#undef NEED_BSD_STRINGS
#undef NEED_SYS_TYPES_H
#undef NEED_FAR_POINTERS
#undef NEED_SHORT_EXTERNAL_NAMES
#undef INCOMPLETE_TYPES_BROKEN

#ifdef _WIN32
#ifndef __RPCNDR_H__
typedef unsigned char boolean;
#endif
#ifndef FALSE
#define FALSE 0
#endif
#ifndef TRUE
#define TRUE 1
#endif
#define HAVE_BOOLEAN
#endif

/* On LP64, long is 64 bits, but jmorecfg.h typedefs INT32 to long.
 * Provide a 32-bit INT32 first and define XMD_H so jmorecfg.h skips its typedef.
 */
#if !defined(_WIN32)
#include <stdint.h>
#define XMD_H 1
typedef int32_t INT32;
typedef int16_t INT16;
#endif

#undef JPEG_HAVE_RGB_CUSTOM
#undef JPEG_USE_RGB_CUSTOM
#undef JPEG_HAVE_FILE_IO_CUSTOM
#undef JPEG_USE_FILE_IO_CUSTOM

#ifdef JPEG_INTERNALS
#undef RIGHT_SHIFT_IS_UNSIGNED
#if defined(_MSC_VER)
#define INLINE __inline
#endif
#endif
]=])

    set(libjpeg_sources
        jaricom.c jcomapi.c jutils.c jerror.c jmemmgr.c jmemnobs.c
        jcapimin.c jcapistd.c jcarith.c jctrans.c jcparam.c jdatadst.c
        jcinit.c jcmaster.c jcmarker.c jcmainct.c jcprepct.c jccoefct.c
        jccolor.c jcsample.c jchuff.c jcdctmgr.c jfdctfst.c jfdctflt.c jfdctint.c
        jdapimin.c jdapistd.c jdarith.c jdtrans.c jdatasrc.c jdmaster.c
        jdinput.c jdmarker.c jdhuff.c jdmainct.c jdcoefct.c jdpostct.c
        jddctmgr.c jidctfst.c jidctflt.c jidctint.c jdsample.c jdcolor.c
        jquant1.c jquant2.c jdmerge.c)
    list(TRANSFORM libjpeg_sources PREPEND "${source_dir}/")

    add_library(jpeg-static STATIC ${libjpeg_sources})
    target_include_directories(jpeg-static PUBLIC
        "${generated_dir}"
        "${source_dir}")
    # clang-cl 会把 MSVC 的 CRT 弃用标成警告。宏去掉弃用属性，不改 third_party。
    target_compile_definitions(jpeg-static PRIVATE _CRT_SECURE_NO_WARNINGS)
    radray_optimize_flags_library(jpeg-static)
    radray_set_build_path(jpeg-static)
endfunction()

radray_add_libjpeg()
