#ifndef RADRAY_FORWARD_BINDING_ABI_HLSL
#define RADRAY_FORWARD_BINDING_ABI_HLSL

// Keep these values synchronized with ForwardPipeline in forward_pipeline.h.
#define RADRAY_FORWARD_OBJECT_BINDING_GROUP 0
#define RADRAY_FORWARD_PIPELINE_BINDING_GROUP 1
#define RADRAY_FORWARD_MATERIAL_BINDING_GROUP 2

#define RADRAY_FORWARD_OBJECT_SPACE space0
#define RADRAY_FORWARD_PIPELINE_SPACE space1
#define RADRAY_FORWARD_MATERIAL_SPACE space2

#endif
